version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    env_file: .env
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - site-network

  php-fpm:
    depends_on:
      - mariadb
    container_name: php-fpm
    restart: unless-stopped
    hostname: php
    build:
        context: ./php-fpm
        dockerfile: Dockerfile
    volumes:
      - ./nginx-html:/var/www/html
    networks:
      - site-network

  webserver:
    depends_on:
      - php-fpm
    image: nginx
    container_name: webserver
    hostname: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    #  - "443:443"
    volumes:
      - ./nginx-html:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt
    networks:
      - site-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./nginx-html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email contact@domain.com --agree-tos --no-eff-email --staging -d domain.com -d www.domain.com
   # command: certonly --webroot --webroot-path=/var/www/html --email contact@domain.com --agree-tos --no-eff-email --force-renewal -d domain.com -d www.domain.com

networks:
  site-network:
    driver: bridge 
